### ISSUE TITLE
Save button lights back up without user action right after a save

### ISSUE THREAD

**Issue by wlycdgr** [expo/snack-web#51] opened 2020-08-24 16:32 UTC
I've been seeing the following a lot while working on my project:

* I make some changes in one of the project files
* The Save button lights up (presumably indicating that I now have unsaved changes)
* I click the Save button
* The "Your Snack was saved" modal pops up
* I dismiss the modal
* At this point, even though I have only just dismissed the modal and have not made any further edits, the Save button counterintuitively lights back up by itself almost immediately. I am able to press it again, at which point I get the modal again. After that second save, the button stays dimmed until I make a new change.

This seems wrong, but more importantly, it feels very bad.

**Comment by IjzerenHein** [comment] 2020-10-23 11:20
Hi! 👋  
Thanks for reporting this. We've fixed this problem recently and I cannot reproduce it anymore.
As such I'm going to close this issue. Feel free to re-open this issue with reproduction steps if you still experience this problem.
regards!

**Closed as completed by IjzerenHein** 2020-10-23 11:20 UTC
