### ISSUE TITLE
Request failed with status 403

### ISSUE THREAD

**Issue by riwu** [expo/snack-web#38] opened 2020-03-12 05:21 UTC
When trying to run https://snack.expo.io/H1nJvH8H8 on S6 / Android 7, I receive the following error. Works fine on other devices. App has the latest version of Expo (v2.14.0, SDK 36) installed. 
![Screenshot_20200312-125214](https://user-images.githubusercontent.com/2226023/76489685-1fb9d100-6464-11ea-8559-e4da297fde32.png)

**Comment by IjzerenHein** [comment] 2020-10-23 09:38
Hi! :wave: I've been unable to reproduce this problem on either Android or iOS using the latest Expo Client (using SDK 36).
I believe this issue has been fixed by recent updates to Snack and the Expo Client. But it may also have been a caching issue. If the problem persists on your device, try reinstalling the Expo client on your Android device to clear its cache.

Feel free to re-open this issue with new reproduction steps if this problem this persists. 👍

**Closed as completed by IjzerenHein** 2020-10-23 09:38 UTC
